# Generated by Django 3.0.2 on 2020-02-13 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_dormitory_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dormitory',
            options={'verbose_name': 'общежитие', 'verbose_name_plural': 'общежития'},
        ),
    ]
