# Generated by Django 3.0.3 on 2020-02-28 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='students',
        ),
    ]
