# Generated by Django 3.0.4 on 2020-03-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_remove_dormitory_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='api.Dormitory', verbose_name='общежитие'),
        ),
    ]
