# Generated by Django 3.0.4 on 2020-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20200329_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=200, verbose_name='главный текст')),
                ('text', models.TextField(max_length=10000, verbose_name='текст')),
                ('is_important', models.BooleanField(default=False, verbose_name='важное ли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновление')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'обращение', 'verbose_name_plural': 'обращения'},
        ),
    ]
