# Generated by Django 3.0.4 on 2020-04-03 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20200331_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='api.Problem', verbose_name='обращение'),
        ),
    ]
