# Generated by Django 3.0.4 on 2020-04-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_auto_20200403_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_from_student',
            field=models.BooleanField(default=True, verbose_name='от студента ли'),
        ),
    ]
