# Generated by Django 3.0.4 on 2020-04-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_message_dormitory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('code', models.CharField(max_length=10, verbose_name='код подтверждения')),
            ],
            options={
                'verbose_name': 'подтверждение',
                'verbose_name_plural': 'подтверждения',
            },
        ),
    ]
