# Generated by Django 3.0.5 on 2020-04-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_auto_20200412_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('A', 'Agent')], default='S', max_length=2,
                                   verbose_name='роль'),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='комната'),
        ),
    ]
