# Generated by Django 3.0.5 on 2020-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_auto_20200428_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('agent', 'Агент поддержки')], default='student',
                                   max_length=20, verbose_name='роль'),
        ),
    ]
