# Generated by Django 3.0.5 on 2020-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_auto_20200428_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('description', models.TextField(max_length=10000, verbose_name='описание')),
                ('target_date', models.DateTimeField(verbose_name='дата проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновление')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
    ]
