# Generated by Django 3.0.5 on 2020-05-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='api.Dormitory', verbose_name='общежитие'),
        ),
        migrations.AddField(
            model_name='notice',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='api.Dormitory', verbose_name='общежитие'),
        ),
    ]
