# Generated by Django 3.0.5 on 2020-05-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_auto_20200518_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='has_new_messages',
            field=models.BooleanField(default=False, verbose_name='есть ли новые сообщения'),
        ),
    ]
