# Generated by Django 3.0.5 on 2020-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0018_problem_has_new_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('O', 'Открыта'), ('C', 'Закрыта')], default='O', max_length=5,
                                   verbose_name='статус'),
        ),
    ]
